### ISSUE TITLE
Python can't import polygames or mcts, but can import tube.

### ISSUE THREAD

**Issue by nikihowe** [AlignmentResearch/polygames#12]
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pypolygames
>>> import tube
>>> import polygames
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: generic_type: type "ForwardPlayer" referenced unknown base type "core::ActorPlayer"
>>> import mcts
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: generic_type: type "MctsPlayer" has a non-default holder type while its base "core::ActorPlayer" does not

**Comment by rhaps0dy** [comment]
Very strange, I've imported it in this order and it worked.

Make sure to `export PYTHONPATH=/polygames` before

**Comment by nikihowe** [comment]
Strange, it works for me too on 4cf3f4a
