### ISSUE TITLE
tictactoe tests still don't work

### ISSUE THREAD

**Issue by nikihowe** [AlignmentResearch/polygames#16]
## Steps to reproduce

  1. _____
  2. _____
  3. _____

## Observed Results

  * What happened?  This could be a description, log output, etc.

## Expected Results

  * What did you expect to happen?

## Relevant Code

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by rhaps0dy** [comment]
I think we gave up in #14 .
