### ISSUE TITLE
`Make` fails when minesweeper and tests are uncommented in CMakeLists.txt

### ISSUE THREAD

**Issue by nikihowe** [AlignmentResearch/polygames#2]
## Steps to reproduce

  1. uncomment lines 54, 57, 58, 60, 62-64, 66, 67 in CMakeLists.txt
  2. run `cmake .. -DCMAKE_BUILD_TYPE=relwithdebinfo -DPYTORCH15=ON -DWITH_LUDII=OFF`
  3. run `make`

## Observed Results

* error

## Expected Results

  * no error

## Relevant Code

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by rhaps0dy** [comment]
solved by #10
